#!/usr/bin/ruby

$images_dir = File.dirname(__FILE__)

#
# converts all the files in icons/*_png to .gif files in icons/*_gif.
#

def write_file(type, images)
  File.open($images_dir + "/../stylesheets/icon_#{type}.css", 'w') do |file|
    images.each do |image|
      str = ".#{image[1]}#{image[0]} {background-image: url(images/#{type}/#{image[0]}/#{image[1]}.#{type})}\n"
      file.write(str)
    end
  end
end

images = []
Dir.chdir($images_dir) do 
  Dir.chdir('png') do
    ['16','48'].each do |dir|
      Dir.chdir(dir) do 
        Dir.glob('*.png') do |png_file|
          images << [dir,png_file.sub(/\.png$/,'')]
          putc '.'; STDOUT.flush;
        end
      end
    end
  end
end

['png','gif'].each do |type|
  write_file(type, images)
end

puts 'done'



