#!/usr/bin/ruby

#
# converts all the files in icons/*_png to .gif files in icons/*_gif.
#

images_dir = File.dirname(__FILE__)

Dir.chdir(images_dir) do 
  Dir.chdir('icons') do
    Dir.glob('*_png/') do |dir|
      Dir.chdir(dir) do 
        Dir.glob('*.png') do |png_file|
          gif_file = '../' + dir.sub('png','gif') + png_file.sub('png','gif')
          putc '.'; STDOUT.flush;
          width, height = `gm identify -format '%wx%h' #{png_file}`.gsub(/\s/,'').split('x')
          system('gm', 'composite', png_file, '../../white.png', '-geometry', "#{width}x#{height}", 'temp_file.png')
          system('gm', 'convert', 'temp_file.png', '-transparent', '#fff', gif_file)
          File.unlink('temp_file.png')
        end
      end
    end
  end
end

puts 'done'



