#!/bin/bash

function usage() {
	cat << EOF
$0: converts svg file(s) to png file(s).
usage: $0 <size> <destination-png-file-or-dir> <source-svg-file(s)>
example: $0 32 pngs/32/ svgs/*.svg
EOF
}

if [ $# -lt 2 ]; then
  usage; exit
fi

size=$1
shift
destf=$1
shift

if [ ! $size -gt 0 ]; then
  echo "bad size: " $size
  usage; exit
fi

if [ $# -lt 1 ]; then
  usage; exit
fi

while [ $# -ge 1 ]; do
  sourcef=$1
  if [ ! -f "$sourcef" ]; then
    echo "bad svg file: " $sourcef
    usage; exit
  fi
  if [ -d "$destf" ]; then
    base=`basename "$sourcef"`
    base=${base%.*}
    destpng=$destf/$base.png
  else
    destpng="$destf"
  fi
  echo "converting $sourcef --> $destpng"
  inkscape -e $destpng -w $size -h $size $sourcef
  shift
done																										

