# IMPORTANT: This file was generated by Cucumber 0.4.3
# Edit at your own peril - it's recommended to regenerate this file
# in the future when you upgrade to a newer version of Cucumber.

config.cache_classes = true # This must be true for Cucumber to operate correctly!

# Log error messages when you accidentally call methods on nil.
config.whiny_nils = true

# Show full error reports and disable caching
config.action_controller.consider_all_requests_local = true
config.action_controller.perform_caching             = false

# Disable request forgery protection in test environment
config.action_controller.allow_forgery_protection    = false

# Tell Action Mailer not to deliver emails to the real world.
# The :test delivery method accumulates sent emails in the
# ActionMailer::Base.deliveries array.
config.action_mailer.perform_deliveries = true
config.action_mailer.delivery_method = :test

config.gem 'cucumber',        :lib => false,        :version => '>=0.4.3' unless File.directory?(File.join(Rails.root, 'vendor/plugins/cucumber'))
config.gem 'webrat',          :lib => false,        :version => '>=0.5.3' unless File.directory?(File.join(Rails.root, 'vendor/plugins/webrat'))
config.gem 'spork',           :lib => false,        :version => '>=0.7.3' unless File.directory?(File.join(Rails.root, 'vendor/plugins/spork'))

ASSET_PRIVATE_STORAGE = "#{RAILS_ROOT}/tmp/private_assets"
ASSET_PUBLIC_STORAGE  = "#{RAILS_ROOT}/tmp/public_assets"

MIN_PASSWORD_STRENGTH = 0

TEST_EMAIL_FILE = RAILS_ROOT + "/tmp/test_emails"

# rails engines are way too verbose, so set engines logging to info:
if defined? Engines
  Engines.logger = ActiveSupport::BufferedLogger.new(config.log_path)
  Engines.logger.level = Logger::INFO
end
