# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "categories", :force => true do |t|
  end

  create_table "groups", :force => true do |t|
    t.column "name", :string
    t.column "parent_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "groups_to_nodes", :force => true do |t|
    t.column "group_id", :integer
    t.column "node_id", :integer
  end

  create_table "nodes", :force => true do |t|
    t.column "name", :string
    t.column "node_type", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "nodes_users", :force => true do |t|
    t.column "node_id", :integer
    t.column "user_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "username", :string
    t.column "display_username", :string
    t.column "language", :string, :limit => 5
    t.column "crypted_password", :string, :limit => 40
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "users_to_users", :force => true do |t|
    t.column "user1_id", :integer
    t.column "user2_id", :integer
  end

end
